# Generated by Django 5.2.2 on 2025-07-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Подтверждён"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="verification_token",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
