# Generated by Django 5.2.2 on 2025-07-26 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_is_verified_customuser_verification_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="verification_token",
        ),
    ]
