# Generated by Django 5.2.2 on 2025-07-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_customuser_is_verified_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("can_block_users", "Может блокировать пользователей"),
                    ("can_block_mailings", "Может блокировать рассылки"),
                    ("view_moderation_panel", "Может просматривать панель модерации"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
