# Generated by Django 5.2.2 on 2025-07-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ["-attempt_time"],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылок",
            },
        ),
    ]
